/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/Academy': RouteRecordInfo<'/Academy', '/Academy', Record<never, never>, Record<never, never>>,
    '/Finance': RouteRecordInfo<'/Finance', '/Finance', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Local': RouteRecordInfo<'/Local', '/Local', Record<never, never>, Record<never, never>>,
    '/Market': RouteRecordInfo<'/Market', '/Market', Record<never, never>, Record<never, never>>,
    '/Policy/': RouteRecordInfo<'/Policy/', '/Policy', Record<never, never>, Record<never, never>>,
    '/Policy/_layout': RouteRecordInfo<'/Policy/_layout', '/Policy/_layout', Record<never, never>, Record<never, never>>,
    '/Policy/CompanyMatching/': RouteRecordInfo<'/Policy/CompanyMatching/', '/Policy/CompanyMatching', Record<never, never>, Record<never, never>>,
    '/Policy/DataDashboard/': RouteRecordInfo<'/Policy/DataDashboard/', '/Policy/DataDashboard', Record<never, never>, Record<never, never>>,
    '/Policy/DataDashboard/CompanyStatus': RouteRecordInfo<'/Policy/DataDashboard/CompanyStatus', '/Policy/DataDashboard/CompanyStatus', Record<never, never>, Record<never, never>>,
    '/Policy/DataDashboard/DataOverview': RouteRecordInfo<'/Policy/DataDashboard/DataOverview', '/Policy/DataDashboard/DataOverview', Record<never, never>, Record<never, never>>,
    '/Policy/DataDashboard/Growthchart': RouteRecordInfo<'/Policy/DataDashboard/Growthchart', '/Policy/DataDashboard/Growthchart', Record<never, never>, Record<never, never>>,
    '/Policy/DataDashboard/IndustrialChain': RouteRecordInfo<'/Policy/DataDashboard/IndustrialChain', '/Policy/DataDashboard/IndustrialChain', Record<never, never>, Record<never, never>>,
    '/Policy/DataDashboard/JiangsuMap': RouteRecordInfo<'/Policy/DataDashboard/JiangsuMap', '/Policy/DataDashboard/JiangsuMap', Record<never, never>, Record<never, never>>,
    '/Policy/DataDashboard/PolicyTable': RouteRecordInfo<'/Policy/DataDashboard/PolicyTable', '/Policy/DataDashboard/PolicyTable', Record<never, never>, Record<never, never>>,
    '/Policy/DataDashboard/WordCloud': RouteRecordInfo<'/Policy/DataDashboard/WordCloud', '/Policy/DataDashboard/WordCloud', Record<never, never>, Record<never, never>>,
    '/Policy/PolicyDatabase/': RouteRecordInfo<'/Policy/PolicyDatabase/', '/Policy/PolicyDatabase', Record<never, never>, Record<never, never>>,
    '/Policy/PolicyDatabase/detail': RouteRecordInfo<'/Policy/PolicyDatabase/detail', '/Policy/PolicyDatabase/detail', Record<never, never>, Record<never, never>>,
    '/Policy/PolicyMatching/': RouteRecordInfo<'/Policy/PolicyMatching/', '/Policy/PolicyMatching', Record<never, never>, Record<never, never>>,
    '/Policy/PolicyMatching/details': RouteRecordInfo<'/Policy/PolicyMatching/details', '/Policy/PolicyMatching/details', Record<never, never>, Record<never, never>>,
    '/Policy/PolicyNews/': RouteRecordInfo<'/Policy/PolicyNews/', '/Policy/PolicyNews', Record<never, never>, Record<never, never>>,
    '/Policy/PolicyNews/details': RouteRecordInfo<'/Policy/PolicyNews/details', '/Policy/PolicyNews/details', Record<never, never>, Record<never, never>>,
    '/Policy/PolicyNews/olddetail': RouteRecordInfo<'/Policy/PolicyNews/olddetail', '/Policy/PolicyNews/olddetail', Record<never, never>, Record<never, never>>,
    '/Policy/SelfAssessment/': RouteRecordInfo<'/Policy/SelfAssessment/', '/Policy/SelfAssessment', Record<never, never>, Record<never, never>>,
    '/Service': RouteRecordInfo<'/Service', '/Service', Record<never, never>, Record<never, never>>,
    '/Supply': RouteRecordInfo<'/Supply', '/Supply', Record<never, never>, Record<never, never>>,
  }
}
